/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TimeNMoney;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;

import javax.swing.JOptionPane;

/**
 *
 * @author Ivo.Oliveira
 */
@SuppressWarnings("serial")
public class Menu_taxa_cambio extends javax.swing.JFrame {
    double rate_usd;
    double rate_akz;
    String username_admin;
    Connection con;
    
    public Menu_taxa_cambio(String user_adm,Connection con_rec) {
    	setResizable(false);
        this.username_admin = user_adm;
        this.con = con_rec;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("odkas.tnm.png")));
//        get_taxas_moeda();
//        preencher_campos();
        carrega_combos();
        get_mes_ano_dados();
    }
    
    @SuppressWarnings("unchecked")
	private void carrega_combos(){
    	
    	//ano
    	Calendar c = Calendar.getInstance();
    	int ano = c.get(Calendar.YEAR);
    	int ano_min = ano - 100;
    	int ano_max = ano + 100;
    	for (int i = ano_min;i<ano_max;i++)
    		field_ano.addItem(i);
    	
    	//mes
    	field_mes.addItem("Janeiro");
    	field_mes.addItem("Fevereiro");
    	field_mes.addItem("Março");
    	field_mes.addItem("Abril");
    	field_mes.addItem("Maio");
    	field_mes.addItem("Junho");
    	field_mes.addItem("Julho");
    	field_mes.addItem("Agosto");
    	field_mes.addItem("Setembro");
    	field_mes.addItem("Outubro");
    	field_mes.addItem("Novembro");
    	field_mes.addItem("Dezembro");
    }
    
    private int get_mes(){
    	return field_mes.getSelectedIndex();
    }
    
    private int get_ano(){
    	return (int)field_ano.getSelectedItem();
    }
    
    private void set_mes(int mes){
    	field_mes.setSelectedIndex(mes);
    }
    
    private void set_ano(int ano){
    	field_ano.setSelectedItem(ano);
    }

    private void get_mes_ano_dados(){
    	Calendar c = Calendar.getInstance();
    	int mes = c.get(Calendar.MONTH);
    	int ano = c.get(Calendar.YEAR);
    	set_mes(mes);
    	set_ano(ano);
    	get_taxas_moeda((mes+1),ano);
    	preencher_campos();
    }
    
    private void preencher_campos(){
        akz_field.setText(String.valueOf(this.rate_akz));
        usd_field.setText(String.valueOf(this.rate_usd));
    }
    
    private void get_taxas_moeda(int mes, int ano){
    	this.rate_usd = 0.00;
    	this.rate_akz = 0.00;
    	try{
            PreparedStatement ps;
            java.sql.ResultSet rs;
            String sql = "select * from TNM_TAXAS_MOEDA where mes = "+mes+" and ano = "+ano;
            ps=this.con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()){
                String moeda = rs.getString("ID_MOEDA");
                double taxa = rs.getDouble("TAXA");
                moeda = moeda.trim().toUpperCase();
                switch (moeda) {
                    case "USD":
                        this.rate_usd = taxa;
                        break;
                    case "AKZ":
                        this.rate_akz = taxa;
                        break;
                }   
            }
            rs.close();
            ps.close();
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            this.setCursor(Cursor.getDefaultCursor());
            new Log_erros_class().write_log_to_file(this.username_admin,e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("rawtypes")
	private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usd_field = new javax.swing.JTextField();
        akz_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        go_button = new javax.swing.JButton();
        field_ano = new javax.swing.JComboBox();
        field_mes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ODKAS - Time &  Money");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EUR");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimeNMoney/Cancel-icon.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimeNMoney/saveicon.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TimeNMoney/money_ex_icon_big.png"))); // NOI18N
        jLabel1.setText("Alterar taxa de câmbio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1.00 USD = ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("1.00 AKZ = ");

        usd_field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        akz_field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("EUR");

        go_button.setText("VER");
        go_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(field_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(go_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(akz_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(usd_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(go_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_ano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(field_mes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usd_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(akz_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        save();
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void go_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_buttonActionPerformed
    	evento_change_combo_mes_ano();
    }//GEN-LAST:event_go_buttonActionPerformed

    private void evento_change_combo_mes_ano(){
    	this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    	int mes = get_mes();
    	int ano = get_ano();
    	get_taxas_moeda((mes+1),ano);
    	preencher_campos();
    	this.setCursor(Cursor.getDefaultCursor());
    }
    
    private void save(){
        try{
            
        double t_usd = Double.parseDouble(usd_field.getText());
        double t_akz = Double.parseDouble(akz_field.getText());
        
        if (this.rate_akz == t_akz && this.rate_usd == t_usd)
            JOptionPane.showMessageDialog(null, "Não fez alterações!");
        else 
            {
        		int mes = get_mes();
        		int ano = get_ano();
        		save_to_bd(t_usd,t_akz,(mes+1),ano);
        		this.rate_akz = t_akz;
        		this.rate_usd = t_usd;
        		JOptionPane.showMessageDialog(null, "Taxas alteradas com sucesso para o mês "+ (mes+1) +" do ano "+ano);
            }
        
        }
        catch(NumberFormatException | HeadlessException e){
            e.printStackTrace();
            this.setCursor(Cursor.getDefaultCursor());
            new Log_erros_class().write_log_to_file(this.username_admin,e);
            if (akz_field.getText().equals("") || usd_field.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Campos vazios, tem que preencher todos os campos!");
            else
                JOptionPane.showMessageDialog(null,"Campos com caracteres inválidos!");
            usd_field.setText("0.0");
            akz_field.setText("0.0");
        }
    }
    
    private void save_to_bd(double usd, double akz,int mes, int ano)
    {
    	try{
    		String sql = "delete from TNM_TAXAS_MOEDA where mes = "+ mes + " and ano = "+ano;
    		PreparedStatement ps = this.con.prepareStatement(sql);
    		ps.executeUpdate();
    		ps.close();
    		
    		sql = "insert into tnm_taxas_moeda (id_moeda,taxa,mes,ano) values (?,?,?,?)";
    		ps = this.con.prepareStatement(sql);
    		ps.setString(1, "USD");
    		ps.setDouble(2, usd);
    		ps.setInt(3, mes);
    		ps.setInt(4, ano);
    		ps.executeUpdate();
    		ps.close();
    		
    		sql = "insert into tnm_taxas_moeda (id_moeda,taxa,mes,ano) values (?,?,?,?)";
    		ps = this.con.prepareStatement(sql);
    		ps.setString(1, "AKZ");
    		ps.setDouble(2, akz);
    		ps.setInt(3, mes);
    		ps.setInt(4, ano);
    		ps.executeUpdate();
    		ps.close();
    	}
    	catch(SQLException e){
    		e.printStackTrace();
    		this.setCursor(Cursor.getDefaultCursor());
    		new Log_erros_class().write_log_to_file(this.username_admin,e);
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akz_field;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox field_ano;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox field_mes;
    private javax.swing.JButton go_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField usd_field;
    // End of variables declaration//GEN-END:variables
}
